services:
  loadbalancer:
    build: ./src/flaskapp/
    ports:
      - "5000:15000"    
    environment:
      - ADDRESS=0.0.0.0
      - PORT=15000

  cdn1:
    cpus: 1.0
    build: ./src/cdn/
    ports:
      - "5001:15000"
    environment:
      - ADDRESS=0.0.0.0
      - PORT=15000
      - OUTSIDE_PORT=5001
      - HOSTNAME=cdn1
      - LOAD_BALANCER_HOSTNAME=loadbalancer
      - LOAD_BALANCER_PORT=15000

  cdn2:
    cpus: 1.0
    build: ./src/cdn/
    ports:
      - "5002:15000"
    environment:
      - ADDRESS=0.0.0.0
      - PORT=15000
      - OUTSIDE_PORT=5002
      - HOSTNAME=cdn2
      - LOAD_BALANCER_HOSTNAME=loadbalancer
      - LOAD_BALANCER_PORT=15000
