services:
  broadcaster:
    build: ./src/broadcaster/

  consumer1:
    build: ./src/consumer/

  consumer2:
    build: ./src/consumer/

  server:
    build: ./src/server/
    ports:
      - "12345:15000"